import type { NextPage } from 'next'
import Head from 'next/head'
import HeroImage from 'components/Hero/HeroImage'
import Hero from '@components/Hero'
import AboutMeSection from '@components/AboutMeSection'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>

      <main className="relative">
        <AboutMeSection />
        <Hero />
      </main>

      <footer></footer>
    </>
  )
}

export default Home
